// Generated by gencpp from file get_pose/GetPose.msg
// DO NOT EDIT!


#ifndef GET_POSE_MESSAGE_GETPOSE_H
#define GET_POSE_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <get_pose/GetPoseRequest.h>
#include <get_pose/GetPoseResponse.h>


namespace get_pose
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace get_pose


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::get_pose::GetPose > {
  static const char* value()
  {
    return "39455a677799109416863d6c9f76cbb1";
  }

  static const char* value(const ::get_pose::GetPose&) { return value(); }
};

template<>
struct DataType< ::get_pose::GetPose > {
  static const char* value()
  {
    return "get_pose/GetPose";
  }

  static const char* value(const ::get_pose::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::get_pose::GetPoseRequest> should match 
// service_traits::MD5Sum< ::get_pose::GetPose > 
template<>
struct MD5Sum< ::get_pose::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::get_pose::GetPose >::value();
  }
  static const char* value(const ::get_pose::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_pose::GetPoseRequest> should match 
// service_traits::DataType< ::get_pose::GetPose > 
template<>
struct DataType< ::get_pose::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::get_pose::GetPose >::value();
  }
  static const char* value(const ::get_pose::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::get_pose::GetPoseResponse> should match 
// service_traits::MD5Sum< ::get_pose::GetPose > 
template<>
struct MD5Sum< ::get_pose::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::get_pose::GetPose >::value();
  }
  static const char* value(const ::get_pose::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_pose::GetPoseResponse> should match 
// service_traits::DataType< ::get_pose::GetPose > 
template<>
struct DataType< ::get_pose::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::get_pose::GetPose >::value();
  }
  static const char* value(const ::get_pose::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GET_POSE_MESSAGE_GETPOSE_H
