// Generated by gencpp from file get_pose/GetPoseRequest.msg
// DO NOT EDIT!


#ifndef GET_POSE_MESSAGE_GETPOSEREQUEST_H
#define GET_POSE_MESSAGE_GETPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace get_pose
{
template <class ContainerAllocator>
struct GetPoseRequest_
{
  typedef GetPoseRequest_<ContainerAllocator> Type;

  GetPoseRequest_()
    : poseData()  {
    }
  GetPoseRequest_(const ContainerAllocator& _alloc)
    : poseData(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _poseData_type;
  _poseData_type poseData;





  typedef boost::shared_ptr< ::get_pose::GetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::get_pose::GetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseRequest_

typedef ::get_pose::GetPoseRequest_<std::allocator<void> > GetPoseRequest;

typedef boost::shared_ptr< ::get_pose::GetPoseRequest > GetPoseRequestPtr;
typedef boost::shared_ptr< ::get_pose::GetPoseRequest const> GetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::get_pose::GetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::get_pose::GetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace get_pose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'get_pose': ['/home/gavin/catkin_ws/src/get_pose/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::get_pose::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::get_pose::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::get_pose::GetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::get_pose::GetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_pose::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_pose::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::get_pose::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39455a677799109416863d6c9f76cbb1";
  }

  static const char* value(const ::get_pose::GetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39455a6777991094ULL;
  static const uint64_t static_value2 = 0x16863d6c9f76cbb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::get_pose::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "get_pose/GetPoseRequest";
  }

  static const char* value(const ::get_pose::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::get_pose::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string poseData\n\
\n\
";
  }

  static const char* value(const ::get_pose::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::get_pose::GetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poseData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::get_pose::GetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::get_pose::GetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "poseData: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.poseData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GET_POSE_MESSAGE_GETPOSEREQUEST_H
